import Head from 'next/head'
import { useState } from 'react'
import { database } from '../firebaseConfig'
import {
  collection,
  doc,
  addDoc,
  getDocs,
  updateDoc,
  deleteDoc
} from 'firebase/firestore';
import Image from 'next/image';

export default function Home() {

  const [lastName, setLastName] = useState(null);
  const [firstName, setFirstName] = useState(null);
  const [sex, setSex] = useState(null);
  const [birthdate, setBirthdate] = useState(null);
  let age = 0;
  const [address, setAddress] = useState(null);
  const databaseReference = collection(database, 'Person');

  const addData = () => {
    addDoc(databaseReference, {
        lastName: lastName,
        firstName: firstName,
        sex: sex,
        birthdate: birthdate,
        address: address
    })
    .then(() => {
        alert("The information was saved successfully.")
        clearInputFields()
    })
    .catch((err) => {
        console.log.apply(err);
    })
  }

  const clearInputFields = () => {
    setLastName('')
    setFirstName('')
    setSex('')
    setBirthdate('')
    setAddress('')
  }

  const buttonClickPrint = () => {
    addData();
    getBirthYear();
    window.print();
    return false;
    
  }

  const getBirthYear = () => {
    //let birthYear = birthdate.slice(0, 4);
    //let currentYear = new Date().getFullYear();
    //age = parseInt(currentYear) - parseInt(birthYear);
    //document.getElementById("calculatedAge").value = age;
    //console.log(age);

    console.log(birthdate) //1983-07-12
    let d1 = birthdate.slice(8,10);
    console.log(d1);
    let m1 = birthdate.slice(5,7);
    console.log(m1);
    let y1 = birthdate.slice(0,4);
    console.log(y1);

    let date = new Date();
    let d2 = date.getDate();
    let m2 = 1 + date.getMonth();
    let y2 = date.getFullYear();
    let month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

    if(d1 > d2) {
      d2 = d2 + month[m2 -1];
      m2 = m2 - 1;
    }
    if(m1 > m2) {
      m2 = m2 + 12;
      y2 = y2 - 1;
    }

    let d = d2 - d1;
    let m = m2 - m1;
    age = y2 - y1;
    document.getElementById("calculatedAge").value = age+' Years '+m+' Months '+d+' Days';
  }

  return (
  <div>
    <div className="print:hidden">
      <Head>
        <title>HELPS Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://liceo.edu.ph/images/site-logo.png" />
      </Head>
      <main>
       

        {/*from the template*/}
        <section className="h-screen">
  <div className="px-6 h-full text-gray-800">
    <div
      className="flex xl:justify-center lg:justify-between justify-center items-center flex-wrap h-full g-6"
    >
      <div
        className="grow-0 shrink-1 md:shrink-0 basis-auto xl:w-6/12 lg:w-6/12 md:w-9/12 mb-12 md:mb-0"
      >
        <Image
          /*src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"*/
          src="https://liceo.edu.ph/images/ico-liceo-big.png"
          className="w-full print:hidden"
          width="1024"
          height="1024"
          alt="Liceo logo"
        />
      </div>
      <div className="xl:ml-20 xl:w-5/12 lg:w-5/12 md:w-8/12 mb-12 md:mb-0">
        <form>
          <div className="flex flex-row items-center justify-center lg:justify-start">
            
          </div>

          <div
            className="flex items-center my-4 before:flex-1 before:border-t before:border-gray-300 before:mt-0.5 after:flex-1 after:border-t after:border-gray-300 after:mt-0.5"
          >
            <p className="print:hidden text-center font-semibold mx-4 mb-0">HELPS Registration v1.00</p>
          </div>

          {/*<!-- Last name input -->*/}
          <div className=" mb-6">
            <input
              type="text"
              name="name"
              id="name"
              required
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              placeholder="Last name"
              onChange={(event) => setLastName(event.target.value)}
              value={lastName}
              
            />
          </div>

          {/*<!-- First name input -->*/}
          <div className="mb-6">
            <input
              type="text"
              className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              placeholder="First name"
              onChange={(event) => setFirstName(event.target.value)}
              value={firstName}
            />
          </div>

          {/*<!-- Sex input -->*/}

          <div className='mb-6'>
            <select 
              className='form-control block w-half px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'
              onChange={(event) => setSex(event.target.value)}
              value={sex}
              required
            >  
              <option>
                Sex
              </option>
              <option>Male</option>
              <option>Female</option>
            </select>
          </div>

          {/*<!-- Birthdate input -->*/}
          <div className="relative">
            <input
              className='form-control block w-half px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none'
              type="date"
              onChange={(event) => setBirthdate(event.target.value)}
              value={birthdate}
            />
            <label className="absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-white-900 px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Birthdate</label>
          </div>

          <br/>

          {/*<!-- Address input -->*/}
          <div className="mb-6">
            <textarea
              className="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              id="formControlInputFirst"
              placeholder="Address"
              onChange={(event) => setAddress(event.target.value)}
              value={address}
            >
            </textarea>
          </div>
          
          <div className="flex justify-between items-center mb-6">
            <div className="form-group form-check">
              <input
                type="checkbox"
                className="print:hidden form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                id="exampleCheck2"
              />
              <label className="print:hidden form-check-label inline-block text-gray-800"
                >I agree to privacy policy.</label
              >
            </div>
          </div>

          <div className="text-center lg:text-left">
            <button
              type="button"
              className="print:hidden inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
              onClick={addData}
            >
              Register
            </button>
          </div>

          <br/>

          <div className="text-center lg:text-left">
            <button
              type="button"
              className="print:mx-0 inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
              onClick={buttonClickPrint}
            >
              Save and Print
            </button>
          </div>

        </form>
      </div>
    </div>
  </div>
</section>

      </main>      
    </div>
    <div className='screen:hidden'>
      <div className="flex justify-center">
        <img
          src="https://liceo.edu.ph/images/site-logo.png"
          className="print:visible "
          alt="Sample image"
        />
      </div>
      

      <div
            className="flex items-center my-4 before:flex-1 before:border-t before:border-gray-300 before:mt-0.5 after:flex-1 after:border-t after:border-gray-300 after:mt-0.5"
      >
          <p className="print:visible text-center font-semibold mx-4 mb-0 text-xl text-gray-200">Personal Information</p>
      </div>

      <div className='flex space-x-4'>
      <div className=" mb-6">
            <label>Last Name</label>
            <input
              type="text"
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              value={lastName}
            />
          </div>

          <div className="mb-6 flex-1">
            <label>First Name</label>
            <input
              type="text"
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              value={firstName}
            />
          </div>
      </div>
      
        <div className='flex space-x-4'>
        <div className=" mb-6">
          <label>Sex</label>
            <input
              type="text"
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              value={sex}
            />
          </div>

          <div className=" mb-6">
          <label>Age</label>
            <input
              id="calculatedAge"
              type="text"
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
            />
          </div>
          <div className='flex justify-self-center'>
            <label className='pt-8'>Signature: ________________</label>
          </div>
        </div>
          

          <div className=" mb-6">
            <label>Address</label>
            <textarea
              type="text"
              className=" form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
              value={address}
            >
            </textarea>
          </div>

          {/*For the consultation and */}
          <div
            className="flex items-center my-4 before:flex-1 before:border-t before:border-gray-300 before:mt-0.5 after:flex-1 after:border-t after:border-gray-300 after:mt-0.5"
          >
            <p className="print:visible text-center font-semibold mx-4 mb-0 text-xl text-gray-200">Consultation</p>
          </div>

          <div>
            <h3 class="mb-4 font-semibold italic text-gray-900 dark:text-white">For</h3>
              <ul class="-mt-4 items-center w-full text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg flex dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="vue-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="vue-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Health</label>
                      </div>
                  </li>
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="react-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="react-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Education</label>
                      </div>
                  </li>
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="angular-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="angular-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Legal</label>
                      </div>
                  </li>
                  <li class="w-full dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="laravel-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="laravel-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Public Service</label>
                      </div>
                  </li>
                </ul>

          </div>
          <div className="mt-2 relative">
            <div className="h-48 form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none">

            </div>
            <label className="absolute text-lg italic text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white dark:bg-white-900 px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Consultation Details</label>
          </div>

          <div className='mt-3'>
            <h3 class="mb-4 font-semibold italic text-gray-900 dark:text-white">Done</h3>
              <ul class="-mt-4 items-center w-full text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg flex dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="vue-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="vue-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Health</label>
                      </div>
                  </li>
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="react-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="react-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Education</label>
                      </div>
                  </li>
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="angular-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="angular-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Legal</label>
                      </div>
                  </li>
                  <li class="w-full dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="laravel-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="laravel-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Public Service</label>
                      </div>
                  </li>
                </ul>

          </div>
          <div className='mt-3'>
            <h3 class="mb-4 font-semibold italic text-gray-900 dark:text-white">Food</h3>
              <ul class="-mt-4 items-center w-full text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg flex dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="vue-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="vue-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Snack</label>
                      </div>
                  </li>
                  <li class="w-full border-b border-gray-200 sm:border-b-0 sm:border-r dark:border-gray-600">
                      <div class="flex items-center pl-3">
                          <input id="react-checkbox-list" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500"/>
                          <label for="react-checkbox-list" class="w-full py-3 ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Lunch</label>
                      </div>
                  </li>
                </ul>

          </div>
    </div>
  </div>
  )
}
